import {
	type ProviderName,
	type ModelInfo,
	anthropicModels,
	bedrockModels,
	cerebrasModels,
	deepSeekModels,
	moonshotModels,
	geminiModels,
	mistralModels,
	openAiNativeModels,
	openAiCodexModels,
	qwenCodeModels,
	vertexModels,
	xaiModels,
	groqModels,
	sambaNovaModels,
	doubaoModels,
	internationalZAiModels,
	fireworksModels,
	featherlessModels,
	minimaxModels,
	basetenModels,
} from "@roo-code/types"

export const MODELS_BY_PROVIDER: Partial<Record<ProviderName, Record<string, ModelInfo>>> = {
	anthropic: anthropicModels,
	bedrock: bedrockModels,
	cerebras: cerebrasModels,
	deepseek: deepSeekModels,
	doubao: doubaoModels,
	moonshot: moonshotModels,
	gemini: geminiModels,
	mistral: mistralModels,
	"openai-native": openAiNativeModels,
	"openai-codex": openAiCodexModels,
	"qwen-code": qwenCodeModels,
	vertex: vertexModels,
	xai: xaiModels,
	groq: groqModels,
	sambanova: sambaNovaModels,
	zai: internationalZAiModels,
	fireworks: fireworksModels,
	featherless: featherlessModels,
	minimax: minimaxModels,
	baseten: basetenModels,
}

export const PROVIDERS = [
	{ value: "openrouter", label: "OpenRouter", proxy: false },
	{ value: "deepinfra", label: "DeepInfra", proxy: false },
	{ value: "anthropic", label: "Anthropic", proxy: false },
	{ value: "cerebras", label: "Cerebras", proxy: false },
	{ value: "gemini", label: "Google Gemini", proxy: false },
	{ value: "doubao", label: "Doubao", proxy: false },
	{ value: "deepseek", label: "DeepSeek", proxy: false },
	{ value: "moonshot", label: "Moonshot", proxy: false },
	{ value: "openai-native", label: "OpenAI", proxy: false },
	{ value: "openai-codex", label: "OpenAI - ChatGPT Plus/Pro", proxy: false },
	{ value: "openai", label: "OpenAI Compatible", proxy: true },
	{ value: "qwen-code", label: "Qwen Code", proxy: false },
	{ value: "vertex", label: "GCP Vertex AI", proxy: false },
	{ value: "bedrock", label: "Amazon Bedrock", proxy: false },
	{ value: "vscode-lm", label: "VS Code LM API", proxy: false },
	{ value: "mistral", label: "Mistral", proxy: false },
	{ value: "lmstudio", label: "LM Studio", proxy: true },
	{ value: "ollama", label: "Ollama", proxy: true },
	{ value: "unbound", label: "Unbound", proxy: false },
	{ value: "requesty", label: "Requesty", proxy: false },
	{ value: "xai", label: "xAI (Grok)", proxy: false },
	{ value: "groq", label: "Groq", proxy: false },
	{ value: "huggingface", label: "Hugging Face", proxy: false },
	{ value: "chutes", label: "Chutes AI", proxy: false },
	{ value: "litellm", label: "LiteLLM", proxy: true },
	{ value: "sambanova", label: "SambaNova", proxy: false },
	{ value: "zai", label: "Z.ai", proxy: false },
	{ value: "fireworks", label: "Fireworks AI", proxy: false },
	{ value: "featherless", label: "Featherless AI", proxy: false },
	{ value: "io-intelligence", label: "IO Intelligence", proxy: false },
	{ value: "roo", label: "Roo Code Router", proxy: false },
	{ value: "vercel-ai-gateway", label: "Vercel AI Gateway", proxy: false },
	{ value: "minimax", label: "MiniMax", proxy: false },
	{ value: "baseten", label: "Baseten", proxy: false },
].sort((a, b) => a.label.localeCompare(b.label))
